/**
 * Priori Site Configuration
 * Generated by Priori Settings — do not edit manually.
 * Commit this file to the priori-site repo root after export.
 */

var PRIORI_CONFIG = {
  CONTACT_EMAIL: ['patentingest', 'gmail.com'],
  FIRM_NAME: 'Priori'
};
